testserver :
	g++ -o testserver testserver.cc -lmymuduo -lpthread -std=c++11 -g
	g++ -o muduoServer muduoServer.cc -lmymuduo -lpthread -std=c++11 -g
	g++ -o muduoClient muduoClient.cc -lmymuduo -lpthread -std=c++11 -g

clean :
	rm -f testserver muduoClient muduoServer